name: checks
on: [push]
jobs:
  dryrun:
    runs-on: mcr.microsoft.com/playwright:v1.41.1-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install poetry
      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry lock --no-update
          poetry install
          poetry run rfbrowser init
      - name: Dry run
        run: |
          poetry run robot --pythonpath . --dryrun .
